services:

  #PHP Service
  ogame-app:
    volumes:
      - ./:/var/www
      - ./php/local.ini:/.usr/local/etc/php/conf.d/local.ini
    build:
      context: .
      dockerfile: Dockerfile
      args:
        OPCACHE_ENABLE: "1" # Enable opcache in production
    image: digitalocean.com/php
    container_name: ogame-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    networks:
      - app-network

  #Nginx Service
  ogame-webserver:
    image: nginx:alpine
    container_name: ogame-webserver
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www:cached
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network

  #MariaDB Service
  ogame-db:
    image: mariadb:11.3.2-jammy
    container_name: ogame-db
    restart: unless-stopped
    tty: true
    volumes:
     - ogame-dbdata:/var/lib/mysql
     - ./mysql/my.cnf:/etc/mysql/my.cnf
    # MariaDB port is not exposed to the host machine in production.
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    secrets:
      - db_root_password
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Secrets
secrets:
  db_root_password:
    file: ./secrets/db_pass

#Volumes
volumes:
  ogame-dbdata:
    driver: local
